dist: trusty
language: android
android:
  components:
    - tools
    - build-tools-28.0.2
    - android-28
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
jdk:
  - oraclejdk8
